# 0322TA

In [72]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

### 小複習

In [1]:
# 炎龍幣換台幣
def yenl2twd(yenl):
    c = 87
    twd = yenl * c
    print((f"{yenl}炎龍幣合{int(twd)}台幣"))

In [2]:
yenl2twd(10)

10炎龍幣合870台幣


In [ ]:
def yenl2twd(yenl, c=87):
    twd = yenl * c
    print((f"{yenl}炎龍幣合{int(twd)}台幣"))

In [8]:
def grade(x):
    if x >=60:
        print("人生起飛！")
    else:
        print("拍拍")

In [9]:
grade(70)

人生起飛！


In [ ]:
grade(59)

### list 與 array的比較

In [12]:
K = list(range(10)) # 0~9的list
L = np.arange(11,17,0.5) # 11~17，每0.5取一個數

In [13]:
K

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
L

array([11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5])

In [15]:
K*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
L*2

array([22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33.])

In [17]:
M = np.array(K)
M

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy的計算功能

In [18]:
L.mean()

13.75

In [19]:
np.mean(L)

13.75

In [22]:
np.median(L)

13.75

In [26]:
L.std()

1.7260262647673315

In [27]:
L.max() # L中的最大值

16.5

In [28]:
L.sum()

165.0

In [29]:
L.cumsum()

array([ 11. ,  22.5,  34.5,  47. ,  60. ,  73.5,  87.5, 102. , 117. ,
       132.5, 148.5, 165. ])

In [31]:
L.prod()

41493667965750.0

In [32]:
L.cumprod()

array([1.10000000e+01, 1.26500000e+02, 1.51800000e+03, 1.89750000e+04,
       2.46675000e+05, 3.33011250e+06, 4.66215750e+07, 6.76012838e+08,
       1.01401926e+10, 1.57172985e+11, 2.51476776e+12, 4.14936680e+13])

In [33]:
N = np.arange(1, 10).reshape(3,3) # 1~9做成3*3的矩陣

In [34]:
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
N.mean()

5.0

In [36]:
N.mean(axis = 0)

array([4., 5., 6.])

In [37]:
N.mean(axis = 1)

array([2., 5., 8.])

In [38]:
N.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [39]:
N.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

In [40]:
N.min(axis = 0)

array([1, 2, 3])

### Numpy random的各種形式

In [47]:
np.random.seed(1)

In [48]:
np.random.randint(10)

5

In [45]:
np.random.seed(1)

In [46]:
np.random.randint(10)

5

In [51]:
num=0
while(num<5):
    np.random.seed(5)
    print(np.random.randint(10))
    num+=1

3
3
3
3
3


In [52]:
num=0
np.random.seed(5)
while(num<5):
    print(np.random.randint(10))
    num+=1

3
6
6
0
9


In [63]:
# 0 <= x < 1
# 裡面輸入維度
np.random.rand()

0.41024163370642774

In [55]:
np.random.rand(2,3)*10

array([[2.51245112, 9.64915293, 6.31766053],
       [8.16660203, 5.66081996, 6.35356206]])

In [59]:
a = np.random.rand(10,10)
a.mean()

0.49106568800806677

In [62]:
num=0
while(num<5):
    a = np.random.rand(10,10)
    print(a.mean())
    num+=1

0.5283409051349498
0.5635003908649714
0.5033243020161755
0.536750188455302
0.4223450893821506


In [64]:
# 標準常態分佈
# 0 mean 1 std
np.random.randn()

-1.7553836058934225

In [65]:
np.random.randn(2,4)

array([[ 1.49484151,  0.20916212, -0.5730907 , -0.55278504],
       [-0.11237351,  0.17807439, -0.86659009,  0.23665326]])

In [69]:
num=0
while(num<5):
    a = np.random.randn(100,100)
    print(a.mean())
    num+=1

0.0052781582716304965
0.0017586446700491656
-0.006442973813094741
0.0063249871375870076
-0.01849431048875838


In [70]:
num=0
while(num<5):
    a = np.random.randn(100,100)
    print(a.std())
    num+=1

1.001438583143748
1.0005400264495712
0.9990150449257011
0.9951492990837615
1.00779242381475


In [74]:
# 隨機整數
# low high size
np.random.randint(10)

6

In [77]:
np.random.randint(10,20)

19

In [78]:
np.random.randint(10, 20, size=(2,4))

array([[19, 15, 13, 10],
       [10, 19, 15, 18]])

In [85]:
# 一個數字類似arange
# 可以從給定的一為array選出指定個數
np.random.choice(10)

7

In [86]:
np.random.choice(10,5)

array([8, 6, 7, 7, 2])

In [87]:
S = ["apple", "banana", "orange", "guava", "tomato"]

In [94]:
np.random.choice(S, size=5)

array(['orange', 'tomato', 'apple', 'tomato', 'guava'], dtype='<U6')

In [95]:
np.random.choice(S, size=5, replace = False)

array(['guava', 'banana', 'orange', 'apple', 'tomato'], dtype='<U6')

In [88]:
np.random.choice(S, size=(3,3))

array([['guava', 'orange', 'tomato'],
       ['orange', 'orange', 'banana'],
       ['orange', 'guava', 'orange']], dtype='<U6')

In [91]:
P = [0.9, 0.1, 0, 0, 0]

In [92]:
np.random.choice(S, size=(3,3), p = P)

array([['apple', 'apple', 'apple'],
       ['apple', 'apple', 'apple'],
       ['apple', 'apple', 'apple']], dtype='<U6')

In [101]:
B = np.array([[1,2,-3], [1,-2,1], [5,-2,-3]])